Did you know that in 2018 98% of the population in Bahrain was using the internet, while in Brazil it was 70% and in Bolivia it was 44%?

In this week’s Figure-Friday we’ll look at the Worldbank’s data on Individuals using the Internet (as a % of the population). It’s important to note that internet users are defined as individuals who have used the Internet (from any location) in the last 3 months. (The Internet can be used via a computer, mobile phone, personal digital assistant, games machine, digital TV etc.)

In [61]:
import pandas as pd

In [62]:
df = pd.read_csv("Metadata_Country_API_IT.NET.USER.ZS_DS2_en_csv_v2_2160.csv")

df.head()

,Country Code,Region,IncomeGroup,SpecialNotes,TableName
0,ABW,Latin America & Caribbean,High income,NaN,Aruba
1,AFE,NaN,NaN,"26 countries, stretching from the Red Sea in t...",Africa Eastern and Southern
2,AFG,South Asia,Low income,The reporting period for national accounts dat...,Afghanistan
3,AFW,NaN,NaN,"22 countries, stretching from the westernmost ...",Africa Western and Central
4,AGO,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...,Angola

In [63]:
df.shape

(265, 5)

In [64]:
df2 = pd.read_csv("API_IT.NET.USER.ZS_DS2_en_csv_v2_2160.csv")
df2.head(2)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aruba,ABW,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,83.78,88.6612,93.5425,97.17,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,12.10,14.3000,15.7000,17.40,19.8,22.8,26.0,29.5,31.4,34.9

In [65]:
df2.shape

(266, 68)

In [77]:
internet_data = df.merge(df2)

internet_data = internet_data.melt(id_vars=internet_data.columns[:8],
                   value_vars= internet_data.columns[8:],
                   var_name= "Year",
                   value_name= "% of Internet Usage"
                  )

internet_data["Year"] = internet_data["Year"].astype("int16")

internet_data = internet_data.dropna(subset="% of Internet Usage") # removing all raws with NA specifically in this columns

internet_data.head(2)

,Country Code,Region,IncomeGroup,SpecialNotes,TableName,Country Name,Indicator Name,Indicator Code,Year,% of Internet Usage
16,BDI,Sub-Saharan Africa,Low income,The World Bank systematically assesses the app...,Burundi,Burundi,Individuals using the Internet (% of population),IT.NET.USER.ZS,1960,0.0
33,BWA,Sub-Saharan Africa,Upper middle income,NaN,Botswana,Botswana,Individuals using the Internet (% of population),IT.NET.USER.ZS,1960,0.0

In [227]:
internet_data.loc[internet_data["Country Name"] != "World"]

,Country Code,Region,IncomeGroup,SpecialNotes,TableName,Country Name,Indicator Name,Indicator Code,Year,% of Internet Usage
16,BDI,Sub-Saharan Africa,Low income,The World Bank systematically assesses the app...,Burundi,Burundi,Individuals using the Internet (% of population),IT.NET.USER.ZS,1960,0.0000
33,BWA,Sub-Saharan Africa,Upper middle income,NaN,Botswana,Botswana,Individuals using the Internet (% of population),IT.NET.USER.ZS,1960,0.0000
90,GRD,Latin America & Caribbean,Upper middle income,NaN,Grenada,Grenada,Individuals using the Internet (% of population),IT.NET.USER.ZS,1960,0.0000
151,MDV,South Asia,Upper middle income,NaN,Maldives,Maldives,Individuals using the Internet (% of population),IT.NET.USER.ZS,1960,0.0000
226,SYR,Middle East & North Africa,Low income,The World Bank systematically assesses the app...,Syrian Arab Republic,Syrian Arab Republic,Individuals using the Internet (% of population),IT.NET.USER.ZS,1960,0.0000
...,...,...,...,...,...,...,...,...,...,...
16935,TSS,NaN,NaN,Sub-Saharan Africa (IDA & IBRD countries) aggr...,Sub-Saharan Africa (IDA & IBRD),Sub-Saharan Africa (IDA & IBRD countries),Individuals using the Internet (% of population),IT.NET.USER.ZS,2023,36.7000
16938,TUR,Europe & Central Asia,Upper middle income,NaN,Türkiye,Turkiye,Individuals using the Internet (% of population),IT.NET.USER.ZS,2023,85.9607
16943,UMC,NaN,NaN,Upper middle income group aggregate. Upper-mid...,Upper middle income,Upper middle income,Individuals using the Internet (% of population),IT.NET.USER.ZS,2023,80.0000
16946,UZB,Europe & Central Asia,Lower middle income,NaN,Uzbekistan,Uzbekistan,Individuals using the Internet (% of population),IT.NET.USER.ZS,2023,89.0136
16951,VNM,East Asia & Pacific,Lower middle income,NaN,Viet Nam,Viet Nam,Individuals using the Internet (% of population),IT.NET.USER.ZS,2023,78.0800

In [280]:
from dash import Dash, html, _dash_renderer, dcc
from dash.dependencies import Output, Input
import dash_mantine_components as dmc
_dash_renderer._set_react_version("18.2.0")

import dash_bootstrap_components as dbc
from dash_bootstrap_templates import load_figure_template

from datetime import datetime, timedelta
from dash_iconify import DashIconify

import pandas as pd 



df = pd.read_csv("Metadata_Country_API_IT.NET.USER.ZS_DS2_en_csv_v2_2160.csv")
df2 = pd.read_csv("API_IT.NET.USER.ZS_DS2_en_csv_v2_2160.csv")
internet_data = df.merge(df2)

internet_data = internet_data.melt(id_vars=internet_data.columns[:8],
                   value_vars= internet_data.columns[8:],
                   var_name= "Year",
                   value_name= "% of Internet Usage"
                  )

internet_data["Year"] = internet_data["Year"].astype("int16")

internet_data = internet_data.dropna(subset="% of Internet Usage") # removing all raws with NA specifically in this columns

internet_data_countries = internet_data.loc[internet_data["Country Name"] != "World"]
internet_data_world = internet_data.loc[internet_data["Country Name"] == "World"]

app = Dash(__name__, external_stylesheets=[dbc.themes.VAPOR] + [dmc.styles.DATES]) # .ALL , here I only want for the dates
load_figure_template("VAPOR")

app.layout = dmc.MantineProvider(
    children=[ 
        dmc.Center("Global Internet Usage: Percentage of Population (historical data from 1960 to 2023, WorldBank)",
                    style={"height": 80, "width": "100%","backgroundColor": "#990066",
                           "fontSize": "2rem", "fontFamly": "Arial", "color": "white"
                          },
                  ),
        html.Br(),
        html.Div(
            style = {"width": "20%"},
           children= [
               dmc.YearPickerInput(
                   id = "years-selection",
                   leftSection=DashIconify(icon="fa:calendar"),
                   minDate=datetime(1960, 1, 1),
                   maxDate=datetime(2023, 1, 1),
                   type="single", #multiple for multiple selection
                   label="Pick Year",
                   clearable = True,
                   placeholder="Pick date",
                   labelProps={"style": {"fontSize": "1.5rem"}},
                    styles={
                        "calendarHeaderLevel": {"color": "blue"  },
                        "placeholder":{"color": "black"}
                    },
               ),
           ]),
    
        dbc.Col(dcc.Graph(id="map",style={"height": "80vh", "width": "80vw"} ), width=9),
        dbc.Row([
            dbc.Col(dcc.Graph(id="region"), width=6),
            dbc.Col(dcc.Graph(id="incomegroup"), width=6),
        ]),
        
        html.Br(),
        dcc.Graph(
            figure = px.line(
                internet_data_world,
                x= "Year",
                y= "% of Internet Usage",
                title= "Internet Usage Trend in the World from 1960 to 2023"
            )
        )
    
   
        
      
    ]
)

@app.callback(
   [
        Output(component_id="map", component_property="figure"),
        Output(component_id="region", component_property="figure"),
        Output(component_id="incomegroup", component_property="figure"),
   ],
    Input(component_id="years-selection", component_property="value")
)
def plot_graph(years):
    if not years:
        avg_internet_percent = (internet_data_countries.groupby(["Country Name"], as_index=False)
                                   .agg({"% of Internet Usage" : "mean"})
                                  )
        fig = px.choropleth(
            data_frame= avg_internet_percent,
            locations= "Country Name",
            color="% of Internet Usage",
            locationmode= "country names",
            scope= "world",
            color_continuous_scale=px.colors.plotlyjs.Rainbow_r,
            title= "Individuals using the Internet (% of population) from 1960 to 2023 - Avg"
        )
        
        avg_internet_region =  (internet_data_countries
                                .groupby("Region", as_index=False)
                                .agg({"% of Internet Usage": "mean"})
                               )
        avg_internet_incomegroup =  (internet_data_countries
                                     .groupby("IncomeGroup", as_index=False)
                                     .agg({"% of Internet Usage": "mean"})
                                    )
        
        bar_region = px.bar(avg_internet_region,
                            x= "Region",
                            y= "% of Internet Usage",
                            title= "Average Percentage of Internet Usage by region to 1960 to 2023"
                           )
        
         
        bar_incomegroup = px.bar(avg_internet_incomegroup,
                            x= "IncomeGroup",
                            y= "% of Internet Usage",
                            title= "Average Percentage of Internet Usage by IncomeGroup to 1960 to 2023"
                           )
        
        
    else:
        selected_year = int(years[:4])
        internet_data_mask = internet_data_countries.query("Year == @selected_year")
        
        avg_internet_percent = (internet_data_mask
                                .groupby(["Country Name"], as_index=False)
                                .agg({"% of Internet Usage" : "mean"})
                                  )
        fig = px.choropleth(
             data_frame= avg_internet_percent,
             locations= "Country Name",
             color="% of Internet Usage",
             locationmode= "country names",
             scope= "world",
             color_continuous_scale=px.colors.plotlyjs.Rainbow_r,
            title= f"Individuals using the Internet (% of population) in {selected_year} by country"
         )
        
        avg_internet_region =  (internet_data_mask
                                .groupby("Region", as_index=False)
                                .agg({"% of Internet Usage": "mean"})
                               )
        avg_internet_incomegroup =  (internet_data_mask
                                     .groupby("IncomeGroup", as_index=False)
                                     .agg({"% of Internet Usage": "mean"})
                                    )
        
        bar_region = px.bar(avg_internet_region,
                            x= "Region",
                            y= "% of Internet Usage",
                            title= f"Average Percentage of Internet Usage by region in {selected_year}"
                           )
        
         
        bar_incomegroup = px.bar(avg_internet_incomegroup,
                            x= "IncomeGroup",
                            y= "% of Internet Usage",
                            title= f"Average Percentage of Internet Usage by IncomeGroup in {selected_year} "
                           )

        
    return fig, bar_region, bar_incomegroup
            

if __name__ == "__main__":
    app.run_server(debug=True, port=2021)